# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/list_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.under_list = QtWidgets.QLabel(self.centralwidget)
        self.under_list.setGeometry(QtCore.QRect(680, 180, 81, 231))
        self.under_list.setTabletTracking(True)
        self.under_list.setStyleSheet("QLabel{\n"
"/* подложка */\n"
"\n"
"position: absolute;\n"
"width: 308px;\n"
"height: 73.5px;\n"
"left: 716px;\n"
"top: 454px;\n"
"\n"
"background: #A0A0A0;\n"
"border-radius: 25px;\n"
"\n"
"}")
        self.under_list.setText("")
        self.under_list.setObjectName("under_list")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(689, 190, 62, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list.sizePolicy().hasHeightForWidth())
        self.list.setSizePolicy(sizePolicy)
        self.list.setMinimumSize(QtCore.QSize(0, 0))
        self.list.setMouseTracking(True)
        self.list.setTabletTracking(True)
        self.list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list.setAutoFillBackground(False)
        self.list.setStyleSheet("QListWidget{\n"
"border: 1px solid;\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: 100px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QListWidget::item{\n"
"padding-top: 10px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    width:8 px;\n"
"    margin: 15px 0px 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(138, 138, 138);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: rgb(95, 95, 95);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(138, 138, 138);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color:  rgb(95, 95, 95);\n"
"    height: 15px;\n"
"    border-typer: solid;\n"
"    border-bottom-left-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(138, 138, 138);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.list.setLineWidth(1)
        self.list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list.setAutoScroll(True)
        self.list.setAutoScrollMargin(16)
        self.list.setAlternatingRowColors(False)
        self.list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.list.setIconSize(QtCore.QSize(56, 56))
        self.list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.list.setMovement(QtWidgets.QListView.Free)
        self.list.setFlow(QtWidgets.QListView.TopToBottom)
        self.list.setProperty("isWrapping", False)
        self.list.setResizeMode(QtWidgets.QListView.Fixed)
        self.list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list.setViewMode(QtWidgets.QListView.ListMode)
        self.list.setModelColumn(0)
        self.list.setUniformItemSizes(True)
        self.list.setBatchSize(100)
        self.list.setWordWrap(False)
        self.list.setSelectionRectVisible(True)
        self.list.setObjectName("list")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../icons/иконка розетка.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../icons/перо иконка.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../icons/энергоблок иконка.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.list.addItem(item)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 120, 581, 351))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setStyleSheet("QGraphicsView{\n"
"border: 10px black;\n"
"\n"
"}")
        self.graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list.setSortingEnabled(False)
        __sortingEnabled = self.list.isSortingEnabled()
        self.list.setSortingEnabled(False)
        self.list.setSortingEnabled(__sortingEnabled)
